package modelos;
// Generated 18-may-2019 13:11:36 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarrosId generated by hbm2java
 */
@Embeddable
public class CarrosId implements java.io.Serializable {

	private int idCarro;
	private int idPedido;
	private String productoSku;
	private String clienteEmail;

	public CarrosId() {
		this.idCarro =-1;
		this.idPedido = -1;
		this.productoSku = "";
		this.clienteEmail = "";
	}

	public CarrosId(int idCarro, int idPedido, String productoSku, String clienteEmail) {
		this.idCarro = idCarro;
		this.idPedido = idPedido;
		this.productoSku = productoSku;
		this.clienteEmail = clienteEmail;
	}

	@Column(name = "ID_CARRO", nullable = false)
	public int getIdCarro() {
		return this.idCarro;
	}

	public void setIdCarro(int idCarro) {
		this.idCarro = idCarro;
	}

	@Column(name = "ID_PEDIDO", nullable = false)
	public int getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(int idPedido) {
		this.idPedido = idPedido;
	}

	@Column(name = "PRODUCTO_SKU", nullable = false, length = 20)
	public String getProductoSku() {
		return this.productoSku;
	}

	public void setProductoSku(String productoSku) {
		this.productoSku = productoSku;
	}

	@Column(name = "CLIENTE_EMAIL", nullable = false, length = 100)
	public String getClienteEmail() {
		return this.clienteEmail;
	}

	public void setClienteEmail(String clienteEmail) {
		this.clienteEmail = clienteEmail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarrosId))
			return false;
		CarrosId castOther = (CarrosId) other;

		return (this.getIdCarro() == castOther.getIdCarro()) && (this.getIdPedido() == castOther.getIdPedido())
				&& ((this.getProductoSku() == castOther.getProductoSku())
						|| (this.getProductoSku() != null && castOther.getProductoSku() != null
								&& this.getProductoSku().equals(castOther.getProductoSku())))
				&& ((this.getClienteEmail() == castOther.getClienteEmail())
						|| (this.getClienteEmail() != null && castOther.getClienteEmail() != null
								&& this.getClienteEmail().equals(castOther.getClienteEmail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCarro();
		result = 37 * result + this.getIdPedido();
		result = 37 * result + (getProductoSku() == null ? 0 : this.getProductoSku().hashCode());
		result = 37 * result + (getClienteEmail() == null ? 0 : this.getClienteEmail().hashCode());
		return result;
	}

}
