package modelos;
// Generated 18-may-2019 11:55:28 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name = "Clientes", schema = "dbo", catalog = "NuperBD")
public class Clientes implements java.io.Serializable {

	private String email;
	private String nombre;
	private String apellidos;
	private String usuario;
	private String clave;
	private Set<Carros> carroses = new HashSet<Carros>(0);
	private Set<Direcciones> direccioneses = new HashSet<Direcciones>(0);
	private Set<PedidosTotal> pedidosTotals = new HashSet<PedidosTotal>(0);

	public Clientes() {
	}

	public Clientes(String email, String nombre, String apellidos, String usuario, String clave) {
		this.email = email;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.usuario = usuario;
		this.clave = clave;
	}

	public Clientes(String email, String nombre, String apellidos, String usuario, String clave, Set<Carros> carroses,
			Set<Direcciones> direccioneses, Set<PedidosTotal> pedidosTotals) {
		this.email = email;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.usuario = usuario;
		this.clave = clave;
		this.carroses = carroses;
		this.direccioneses = direccioneses;
		this.pedidosTotals = pedidosTotals;
	}

	@Id

	@Column(name = "EMAIL", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "NOMBRE", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDOS", nullable = false, length = 50)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Column(name = "USUARIO", nullable = false, length = 50)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "CLAVE", nullable = false, length = 100)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<Carros> getCarroses() {
		return this.carroses;
	}

	public void setCarroses(Set<Carros> carroses) {
		this.carroses = carroses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<Direcciones> getDireccioneses() {
		return this.direccioneses;
	}

	public void setDireccioneses(Set<Direcciones> direccioneses) {
		this.direccioneses = direccioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientes")
	public Set<PedidosTotal> getPedidosTotals() {
		return this.pedidosTotals;
	}

	public void setPedidosTotals(Set<PedidosTotal> pedidosTotals) {
		this.pedidosTotals = pedidosTotals;
	}

}
