package modelos;
// Generated 18-may-2019 11:55:28 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direcciones generated by hbm2java
 */
@Entity
@Table(name = "Direcciones", schema = "dbo", catalog = "NuperBD")
public class Direcciones implements java.io.Serializable {

	private DireccionesId id;
	private Clientes clientes;
	private String ciudad;
	private String observaciones;

	public Direcciones() {
	}

	public Direcciones(DireccionesId id, Clientes clientes, String ciudad) {
		this.id = id;
		this.clientes = clientes;
		this.ciudad = ciudad;
	}

	public Direcciones(DireccionesId id, Clientes clientes, String ciudad, String observaciones) {
		this.id = id;
		this.clientes = clientes;
		this.ciudad = ciudad;
		this.observaciones = observaciones;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "clienteEmail", column = @Column(name = "CLIENTE_EMAIL", nullable = false, length = 100)),
			@AttributeOverride(name = "cp", column = @Column(name = "CP", nullable = false, length = 20)),
			@AttributeOverride(name = "pais", column = @Column(name = "PAIS", nullable = false, length = 50)),
			@AttributeOverride(name = "localidad", column = @Column(name = "LOCALIDAD", nullable = false, length = 50)),
			@AttributeOverride(name = "calle", column = @Column(name = "CALLE", nullable = false, length = 50)),
			@AttributeOverride(name = "numero", column = @Column(name = "NUMERO", nullable = false, length = 50)),
			@AttributeOverride(name = "bloque", column = @Column(name = "BLOQUE", nullable = false, length = 50)),
			@AttributeOverride(name = "piso", column = @Column(name = "PISO", nullable = false, length = 50)),
			@AttributeOverride(name = "puerta", column = @Column(name = "PUERTA", nullable = false, length = 50)) })
	public DireccionesId getId() {
		return this.id;
	}

	public void setId(DireccionesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENTE_EMAIL", nullable = false, insertable = false, updatable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "CIUDAD", nullable = false, length = 50)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "OBSERVACIONES", length = 500)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
