package modelos;
// Generated 18-may-2019 11:55:28 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DireccionesId generated by hbm2java
 */
@Embeddable
public class DireccionesId implements java.io.Serializable {

	private String clienteEmail;
	private String cp;
	private String pais;
	private String localidad;
	private String calle;
	private String numero;
	private String bloque;
	private String piso;
	private String puerta;

	public DireccionesId() {
	}

	public DireccionesId(String clienteEmail, String cp, String pais, String localidad, String calle, String numero,
			String bloque, String piso, String puerta) {
		this.clienteEmail = clienteEmail;
		this.cp = cp;
		this.pais = pais;
		this.localidad = localidad;
		this.calle = calle;
		this.numero = numero;
		this.bloque = bloque;
		this.piso = piso;
		this.puerta = puerta;
	}

	@Column(name = "CLIENTE_EMAIL", nullable = false, length = 100)
	public String getClienteEmail() {
		return this.clienteEmail;
	}

	public void setClienteEmail(String clienteEmail) {
		this.clienteEmail = clienteEmail;
	}

	@Column(name = "CP", nullable = false, length = 20)
	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	@Column(name = "PAIS", nullable = false, length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "LOCALIDAD", nullable = false, length = 50)
	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	@Column(name = "CALLE", nullable = false, length = 50)
	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	@Column(name = "NUMERO", nullable = false, length = 50)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "BLOQUE", nullable = false, length = 50)
	public String getBloque() {
		return this.bloque;
	}

	public void setBloque(String bloque) {
		this.bloque = bloque;
	}

	@Column(name = "PISO", nullable = false, length = 50)
	public String getPiso() {
		return this.piso;
	}

	public void setPiso(String piso) {
		this.piso = piso;
	}

	@Column(name = "PUERTA", nullable = false, length = 50)
	public String getPuerta() {
		return this.puerta;
	}

	public void setPuerta(String puerta) {
		this.puerta = puerta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DireccionesId))
			return false;
		DireccionesId castOther = (DireccionesId) other;

		return ((this.getClienteEmail() == castOther.getClienteEmail()) || (this.getClienteEmail() != null
				&& castOther.getClienteEmail() != null && this.getClienteEmail().equals(castOther.getClienteEmail())))
				&& ((this.getCp() == castOther.getCp()) || (this.getCp() != null && castOther.getCp() != null
						&& this.getCp().equals(castOther.getCp())))
				&& ((this.getPais() == castOther.getPais()) || (this.getPais() != null && castOther.getPais() != null
						&& this.getPais().equals(castOther.getPais())))
				&& ((this.getLocalidad() == castOther.getLocalidad()) || (this.getLocalidad() != null
						&& castOther.getLocalidad() != null && this.getLocalidad().equals(castOther.getLocalidad())))
				&& ((this.getCalle() == castOther.getCalle()) || (this.getCalle() != null
						&& castOther.getCalle() != null && this.getCalle().equals(castOther.getCalle())))
				&& ((this.getNumero() == castOther.getNumero()) || (this.getNumero() != null
						&& castOther.getNumero() != null && this.getNumero().equals(castOther.getNumero())))
				&& ((this.getBloque() == castOther.getBloque()) || (this.getBloque() != null
						&& castOther.getBloque() != null && this.getBloque().equals(castOther.getBloque())))
				&& ((this.getPiso() == castOther.getPiso()) || (this.getPiso() != null && castOther.getPiso() != null
						&& this.getPiso().equals(castOther.getPiso())))
				&& ((this.getPuerta() == castOther.getPuerta()) || (this.getPuerta() != null
						&& castOther.getPuerta() != null && this.getPuerta().equals(castOther.getPuerta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getClienteEmail() == null ? 0 : this.getClienteEmail().hashCode());
		result = 37 * result + (getCp() == null ? 0 : this.getCp().hashCode());
		result = 37 * result + (getPais() == null ? 0 : this.getPais().hashCode());
		result = 37 * result + (getLocalidad() == null ? 0 : this.getLocalidad().hashCode());
		result = 37 * result + (getCalle() == null ? 0 : this.getCalle().hashCode());
		result = 37 * result + (getNumero() == null ? 0 : this.getNumero().hashCode());
		result = 37 * result + (getBloque() == null ? 0 : this.getBloque().hashCode());
		result = 37 * result + (getPiso() == null ? 0 : this.getPiso().hashCode());
		result = 37 * result + (getPuerta() == null ? 0 : this.getPuerta().hashCode());
		return result;
	}

}
