package modelos;
// Generated 18-may-2019 11:55:28 by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name = "Pedidos", schema = "dbo", catalog = "NuperBD")
public class Pedidos implements java.io.Serializable {

	private PedidosId id;
	private Productos productos;
	private int unidades;
	private double precioUnitario;
	private double precioTotal;
	private Set<Carros> carroses = new HashSet<Carros>(0);

	public Pedidos() {
	}

	public Pedidos(PedidosId id, Productos productos, int unidades, double precioUnitario, double precioTotal) {
		this.id = id;
		this.productos = productos;
		this.unidades = unidades;
		this.precioUnitario = precioUnitario;
		this.precioTotal = precioTotal;
	}

	public Pedidos(PedidosId id, Productos productos, int unidades, double precioUnitario, double precioTotal,
			Set<Carros> carroses) {
		this.id = id;
		this.productos = productos;
		this.unidades = unidades;
		this.precioUnitario = precioUnitario;
		this.precioTotal = precioTotal;
		this.carroses = carroses;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPedido", column = @Column(name = "ID_PEDIDO", nullable = false)),
			@AttributeOverride(name = "productoSku", column = @Column(name = "PRODUCTO_SKU", nullable = false, length = 20)) })
	public PedidosId getId() {
		return this.id;
	}

	public void setId(PedidosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_SKU", nullable = false, insertable = false, updatable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "UNIDADES", nullable = false)
	public int getUnidades() {
		return this.unidades;
	}

	public void setUnidades(int unidades) {
		this.unidades = unidades;
	}

	@Column(name = "PRECIO_UNITARIO", nullable = false, precision = 53, scale = 0)
	public double getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(double precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "PRECIO_TOTAL", nullable = false, precision = 53, scale = 0)
	public double getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(double precioTotal) {
		this.precioTotal = precioTotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedidos")
	public Set<Carros> getCarroses() {
		return this.carroses;
	}

	public void setCarroses(Set<Carros> carroses) {
		this.carroses = carroses;
	}

}
