package modelos;
// Generated 19-may-2019 16:40:36 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import modelos.Clientes;

/**
 * PedidosTotal generated by hbm2java
 */
@Entity
@Table(name = "Pedidos_Total", schema = "dbo", catalog = "NuperBD")
public class PedidosTotal implements java.io.Serializable {

	private PedidosTotalId id;
	private Clientes clientes;
	private double totalPedido;

	public PedidosTotal() {
	}

	public PedidosTotal(PedidosTotalId id, Clientes clientes, double totalPedido) {
		this.id = id;
		this.clientes = clientes;
		this.totalPedido = totalPedido;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPedido", column = @Column(name = "ID_PEDIDO", nullable = false)),
			@AttributeOverride(name = "clienteEmail", column = @Column(name = "CLIENTE_EMAIL", nullable = false, length = 100)) })
	public PedidosTotalId getId() {
		return this.id;
	}

	public void setId(PedidosTotalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLIENTE_EMAIL", nullable = false, insertable = false, updatable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "TOTAL_PEDIDO", nullable = false, precision = 53, scale = 0)
	public double getTotalPedido() {
		return this.totalPedido;
	}

	public void setTotalPedido(double totalPedido) {
		this.totalPedido = totalPedido;
	}

}
