package modelos;
// Generated 18-may-2019 11:55:28 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Valoraciones generated by hbm2java
 */
@Entity
@Table(name = "Valoraciones", schema = "dbo", catalog = "NuperBD")
public class Valoraciones implements java.io.Serializable {

	private int idValoracion;
	private Productos productos;
	private String texto;
	private Integer puntuacion;

	public Valoraciones() {
	}

	public Valoraciones(int idValoracion) {
		this.idValoracion = idValoracion;
	}

	public Valoraciones(int idValoracion, Productos productos, String texto, Integer puntuacion) {
		this.idValoracion = idValoracion;
		this.productos = productos;
		this.texto = texto;
		this.puntuacion = puntuacion;
	}

	@Id

	@Column(name = "ID_VALORACION", unique = true, nullable = false)
	public int getIdValoracion() {
		return this.idValoracion;
	}

	public void setIdValoracion(int idValoracion) {
		this.idValoracion = idValoracion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCTO_SKU")
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "TEXTO", length = 500)
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Column(name = "PUNTUACION")
	public Integer getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(Integer puntuacion) {
		this.puntuacion = puntuacion;
	}

}
